apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: jenkins-sc
  hostPath:
    path: /mnt/data/jenkins