apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mohamedbstar413/test-git.git
      revision: main
      directories:
        - path: argocd/argocd-applications/*
  template:
    metadata:
      name: '{{.path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/mohamedbstar413/test-git.git
        targetRevision: main
        path: '{{path}}'          # value from app.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'   # value from app.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true