apiVersion: v1
kind: Service

metadata:
  name: front-service
  namespace: front-ns
{{- if .Values.service.annotations }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}

spec:
  selector:
{{- include "frontend.selectorLabels" . | nindent 4}}
  type: {{ .Values.service.type }}
  ports:
{{- toYaml .Values.service.ports | nindent 4 }}

