apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: db-ns
data:
  init.sql: |-
{{ .Files.Get "files/init.sql" | indent 4 }}
  my.cnf: |-
{{ .Files.Get "files/my.cnf" | indent 4 }}
