apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.volumeClaimName }}
  namespace: db-ns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
