apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: db-ns
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}