apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-provider-aws-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    targetRevision: 0.3.0
    chart: secrets-store-csi-driver-provider-aws
    helm:
      releaseName: secrets-store-aws-provider
        

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true